set(_AMENT_PACKAGE_NAME "dynamixel_workbench")
set(dynamixel_workbench_VERSION "2.2.5")
set(dynamixel_workbench_MAINTAINER "Pyo <pyo@robotis.com>")
set(dynamixel_workbench_BUILD_DEPENDS )
set(dynamixel_workbench_BUILDTOOL_DEPENDS "ament_cmake")
set(dynamixel_workbench_BUILD_EXPORT_DEPENDS )
set(dynamixel_workbench_BUILDTOOL_EXPORT_DEPENDS )
set(dynamixel_workbench_EXEC_DEPENDS "dynamixel_workbench_toolbox")
set(dynamixel_workbench_TEST_DEPENDS )
set(dynamixel_workbench_GROUP_DEPENDS )
set(dynamixel_workbench_MEMBER_OF_GROUPS )
set(dynamixel_workbench_DEPRECATED "")
set(dynamixel_workbench_EXPORT_TAGS)
list(APPEND dynamixel_workbench_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
