set(_AMENT_PACKAGE_NAME "ros2_optitrack_bridge")
set(ros2_optitrack_bridge_VERSION "1.0.0")
set(ros2_optitrack_bridge_MAINTAINER "Jaewoo Lee <jaewoolee930@snu.ac.kr>")
set(ros2_optitrack_bridge_BUILD_DEPENDS )
set(ros2_optitrack_bridge_BUILDTOOL_DEPENDS "ament_cmake")
set(ros2_optitrack_bridge_BUILD_EXPORT_DEPENDS )
set(ros2_optitrack_bridge_BUILDTOOL_EXPORT_DEPENDS )
set(ros2_optitrack_bridge_EXEC_DEPENDS )
set(ros2_optitrack_bridge_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(ros2_optitrack_bridge_GROUP_DEPENDS )
set(ros2_optitrack_bridge_MEMBER_OF_GROUPS )
set(ros2_optitrack_bridge_DEPRECATED "")
set(ros2_optitrack_bridge_EXPORT_TAGS)
list(APPEND ros2_optitrack_bridge_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
